### ISSUE TITLE
武汉红十字会与湖北红十字会是不同的机构，页面主题和内容应注意区分

### ISSUE THREAD

**Issue by wertycn** [WeileiZeng/red-cross#10]
如题，当前页码标题为武汉红十字会监工，但页面内容均为湖北红十字会，应该注意区分，避免误导

**Comment by WeileiZeng** [comment]
谢谢！我们希望同时监督两个红会。目前正在添加武汉红十字会的内容。

**Comment by WeileiZeng** [comment]
页面已经分开了，感谢反馈。后期还会增加韩红基金会作为对比。
