### ISSUE TITLE
招聘信息处理员 审核员等 若干

### ISSUE THREAD

**Issue by WeileiZeng** [WeileiZeng/red-cross#2]
一起加入吧

**Comment by geniuszxd** [comment]
顶你。我是个有正义感的技术渣，向你学习！！

**Comment by WeileiZeng** [comment]
@geniuszxd 页面开发工作量不大。目前比较需要的是整理数据来源。规划页面信息展示方式。欢迎加入。

**Comment by WeileiZeng** [comment]
做一个时间轴，给出一些大事件的新闻链接。有兴趣可以把这一块新闻整理一下
