### ISSUE TITLE
建议使用Google Docs，真诚安利

### ISSUE THREAD

**Issue by leeweizhe1993** [WeileiZeng/red-cross#3]
[谷歌文档](docs.google.com)

**Comment by GindaChen** [comment]
Failed to access the link...

**Comment by GindaChen** [comment]
另外国内不知道能不能Acces到Google Doc？虽然我也很喜欢用GoogleDoc

**Comment by WeileiZeng** [comment]
目前数据不大。保存在data 文件夹里的csv文件中。之后数据量大的话，得考虑一下怎么处理。谷歌的问题是国内不方便打开

**Comment by GindaChen** [comment]
如果你会用AWS的话 简单开一个S3储存就好了
