### ISSUE TITLE
建议和红十取得联系，听一下他们的需求

### ISSUE THREAD

**Issue by Bdl-1989** [WeileiZeng/red-cross#5]
需不需要软件方面的支持？

**Comment by WeileiZeng** [comment]
谢谢！现在需要画图，比如首页第一个表的增长曲线。

或者你有推荐其他软件？

**Comment by WeileiZeng** [comment]
对当地物流以及捐赠的支持请参考wuhan2020项目。本站主要是做一个相对独立客观的信息公示，用于公众监督和参考。

**Comment by Bdl-1989** [comment]
> 谢谢！现在需要画图，比如首页第一个表的增长曲线。
> 
> 或者你有推荐其他软件？

可以试下Bokeh

**Comment by Bdl-1989** [comment]
> 对当地物流以及捐赠的支持请参考wuhan2020项目。本站主要是做一个相对独立客观的信息公示，用于公众监督和参考。

只是个建议，说不定他们需要这方面的support来提高工作效率。监督只是一方面，真是把事情办好才是大家希望的。
