### ISSUE TITLE
news 404 建议改为 web.archive

### ISSUE THREAD

**Issue by inkydragon** [WeileiZeng/red-cross#9]
https://mp.weixin.qq.com/s/ts4v6aSPrL26DVt6dm63-A

**Comment by WeileiZeng** [comment]
没懂，可否解释一下是什么意思？

我打开这个链接以后显示

此内容因违规无法查看

**Comment by inkydragon** [comment]
就是说这个新闻没了（HTTP 404：Not Found），建议引用的新闻都采用 https://web.archive.org/ 备份。

https://web.archive.org/web/20200201163506/https://mp.weixin.qq.com/s/ts4v6aSPrL26DVt6dm63-A

**Comment by WeileiZeng** [comment]
明白了。谢谢！
